// Financial instruments data
export interface FinancialInstrument {
  symbol: string;
  name: string;
  category: 'stocks' | 'indices' | 'bonds' | 'crypto' | 'commodities';
  price?: number;
  change?: number;
  changePercent?: number;
  logo?: string;
  description?: string;
}

export const FINANCIAL_INSTRUMENTS: FinancialInstrument[] = [
  // Stocks - Major US Companies
  { symbol: 'AAPL', name: 'Apple Inc.', category: 'stocks', description: 'Technology company' },
  { symbol: 'MSFT', name: 'Microsoft Corporation', category: 'stocks', description: 'Technology company' },
  { symbol: 'GOOGL', name: 'Alphabet Inc.', category: 'stocks', description: 'Technology company' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.', category: 'stocks', description: 'E-commerce and cloud computing' },
  { symbol: 'TSLA', name: 'Tesla Inc.', category: 'stocks', description: 'Electric vehicles and clean energy' },
  { symbol: 'META', name: 'Meta Platforms Inc.', category: 'stocks', description: 'Social media and metaverse' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation', category: 'stocks', description: 'Graphics processing units' },
  { symbol: 'NFLX', name: 'Netflix Inc.', category: 'stocks', description: 'Streaming entertainment' },
  { symbol: 'BABA', name: 'Alibaba Group', category: 'stocks', description: 'Chinese e-commerce' },
  { symbol: 'V', name: 'Visa Inc.', category: 'stocks', description: 'Payment processing' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', category: 'stocks', description: 'Healthcare and pharmaceuticals' },
  { symbol: 'WMT', name: 'Walmart Inc.', category: 'stocks', description: 'Retail corporation' },
  { symbol: 'PG', name: 'Procter & Gamble', category: 'stocks', description: 'Consumer goods' },
  { symbol: 'UNH', name: 'UnitedHealth Group', category: 'stocks', description: 'Healthcare services' },
  { symbol: 'HD', name: 'The Home Depot', category: 'stocks', description: 'Home improvement retail' },
  { symbol: 'MA', name: 'Mastercard Inc.', category: 'stocks', description: 'Payment processing' },
  { symbol: 'DIS', name: 'The Walt Disney Company', category: 'stocks', description: 'Entertainment and media' },
  { symbol: 'ADBE', name: 'Adobe Inc.', category: 'stocks', description: 'Software and creative tools' },
  { symbol: 'NFLX', name: 'Netflix Inc.', category: 'stocks', description: 'Streaming services' },
  { symbol: 'CRM', name: 'Salesforce Inc.', category: 'stocks', description: 'Cloud computing' },
  { symbol: 'PYPL', name: 'PayPal Holdings', category: 'stocks', description: 'Digital payments' },
  { symbol: 'INTC', name: 'Intel Corporation', category: 'stocks', description: 'Semiconductor manufacturing' },
  { symbol: 'CSCO', name: 'Cisco Systems', category: 'stocks', description: 'Networking equipment' },
  { symbol: 'PFE', name: 'Pfizer Inc.', category: 'stocks', description: 'Pharmaceutical company' },
  { symbol: 'KO', name: 'The Coca-Cola Company', category: 'stocks', description: 'Beverage company' },
  { symbol: 'PEP', name: 'PepsiCo Inc.', category: 'stocks', description: 'Food and beverage' },
  { symbol: 'ABBV', name: 'AbbVie Inc.', category: 'stocks', description: 'Biopharmaceutical company' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific', category: 'stocks', description: 'Life sciences' },
  { symbol: 'ACN', name: 'Accenture plc', category: 'stocks', description: 'Consulting services' },
  { symbol: 'AVGO', name: 'Broadcom Inc.', category: 'stocks', description: 'Semiconductor company' },
  { symbol: 'TXN', name: 'Texas Instruments', category: 'stocks', description: 'Semiconductor company' },
  { symbol: 'QCOM', name: 'QUALCOMM Inc.', category: 'stocks', description: 'Wireless technology' },
  { symbol: 'COST', name: 'Costco Wholesale', category: 'stocks', description: 'Membership warehouse club' },
  { symbol: 'DHR', name: 'Danaher Corporation', category: 'stocks', description: 'Life sciences and diagnostics' },
  { symbol: 'LIN', name: 'Linde plc', category: 'stocks', description: 'Industrial gases' },
  { symbol: 'NEE', name: 'NextEra Energy', category: 'stocks', description: 'Electric utility company' },
  { symbol: 'MCD', name: 'McDonald\'s Corporation', category: 'stocks', description: 'Fast food restaurant' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb', category: 'stocks', description: 'Pharmaceutical company' },
  { symbol: 'IBM', name: 'International Business Machines', category: 'stocks', description: 'Technology and consulting' },
  { symbol: 'AMGN', name: 'Amgen Inc.', category: 'stocks', description: 'Biotechnology company' },
  { symbol: 'HON', name: 'Honeywell International', category: 'stocks', description: 'Aerospace and building technologies' },
  { symbol: 'UPS', name: 'United Parcel Service', category: 'stocks', description: 'Package delivery and logistics' },
  { symbol: 'LOW', name: 'Lowe\'s Companies', category: 'stocks', description: 'Home improvement retail' },
  { symbol: 'SBUX', name: 'Starbucks Corporation', category: 'stocks', description: 'Coffee chain' },
  { symbol: 'CAT', name: 'Caterpillar Inc.', category: 'stocks', description: 'Construction and mining equipment' },
  { symbol: 'LMT', name: 'Lockheed Martin', category: 'stocks', description: 'Aerospace and defense' },
  { symbol: 'MDT', name: 'Medtronic plc', category: 'stocks', description: 'Medical devices' },
  { symbol: 'GS', name: 'The Goldman Sachs Group', category: 'stocks', description: 'Investment banking' },
  { symbol: 'ISRG', name: 'Intuitive Surgical', category: 'stocks', description: 'Robotic surgery systems' },
  { symbol: 'SPGI', name: 'S&P Global Inc.', category: 'stocks', description: 'Financial information services' },
  { symbol: 'BLK', name: 'BlackRock Inc.', category: 'stocks', description: 'Investment management' },

  // Major Indices
  { symbol: '^GSPC', name: 'S&P 500', category: 'indices', description: 'US large-cap stock index' },
  { symbol: '^DJI', name: 'Dow Jones Industrial Average', category: 'indices', description: 'US stock market index' },
  { symbol: '^IXIC', name: 'NASDAQ Composite', category: 'indices', description: 'US technology-heavy index' },
  { symbol: '^RUT', name: 'Russell 2000', category: 'indices', description: 'US small-cap stock index' },
  { symbol: '^VIX', name: 'CBOE Volatility Index', category: 'indices', description: 'Market volatility index' },
  { symbol: '^FTSE', name: 'FTSE 100', category: 'indices', description: 'UK stock market index' },
  { symbol: '^GDAXI', name: 'DAX', category: 'indices', description: 'German stock market index' },
  { symbol: '^FCHI', name: 'CAC 40', category: 'indices', description: 'French stock market index' },
  { symbol: '^N225', name: 'Nikkei 225', category: 'indices', description: 'Japanese stock market index' },
  { symbol: '^HSI', name: 'Hang Seng Index', category: 'indices', description: 'Hong Kong stock market index' },
  { symbol: '^AXJO', name: 'ASX 200', category: 'indices', description: 'Australian stock market index' },
  { symbol: '^BVSP', name: 'Bovespa Index', category: 'indices', description: 'Brazilian stock market index' },
  { symbol: '^MXX', name: 'IPC Mexico', category: 'indices', description: 'Mexican stock market index' },
  { symbol: '^KS11', name: 'KOSPI', category: 'indices', description: 'South Korean stock market index' },
  { symbol: '^TWII', name: 'Taiwan Weighted', category: 'indices', description: 'Taiwan stock market index' },
  { symbol: '^SSEC', name: 'Shanghai Composite', category: 'indices', description: 'Chinese stock market index' },
  { symbol: '^STI', name: 'Straits Times Index', category: 'indices', description: 'Singapore stock market index' },
  { symbol: '^KLSE', name: 'KLCI', category: 'indices', description: 'Malaysia stock market index' },
  { symbol: '^SET', name: 'SET Index', category: 'indices', description: 'Thailand stock market index' },
  { symbol: '^JKSE', name: 'Jakarta Composite', category: 'indices', description: 'Indonesia stock market index' },

  // Bonds
  { symbol: '^TNX', name: '10-Year Treasury Yield', category: 'bonds', description: 'US 10-year government bond yield' },
  { symbol: '^FVX', name: '5-Year Treasury Yield', category: 'bonds', description: 'US 5-year government bond yield' },
  { symbol: '^TYX', name: '30-Year Treasury Yield', category: 'bonds', description: 'US 30-year government bond yield' },
  { symbol: '^IRX', name: '3-Month Treasury Yield', category: 'bonds', description: 'US 3-month government bond yield' },
  { symbol: 'TLT', name: 'iShares 20+ Year Treasury Bond ETF', category: 'bonds', description: 'Long-term US Treasury ETF' },
  { symbol: 'IEF', name: 'iShares 7-10 Year Treasury Bond ETF', category: 'bonds', description: 'Medium-term US Treasury ETF' },
  { symbol: 'SHY', name: 'iShares 1-3 Year Treasury Bond ETF', category: 'bonds', description: 'Short-term US Treasury ETF' },
  { symbol: 'LQD', name: 'iShares iBoxx Investment Grade Corporate Bond ETF', category: 'bonds', description: 'Corporate bond ETF' },
  { symbol: 'HYG', name: 'iShares iBoxx High Yield Corporate Bond ETF', category: 'bonds', description: 'High-yield corporate bond ETF' },
  { symbol: 'AGG', name: 'iShares Core US Aggregate Bond ETF', category: 'bonds', description: 'Total bond market ETF' },
  { symbol: 'BND', name: 'Vanguard Total Bond Market ETF', category: 'bonds', description: 'Total bond market ETF' },
  { symbol: 'GOVT', name: 'iShares US Treasury Bond ETF', category: 'bonds', description: 'US Treasury bond ETF' },
  { symbol: 'TIPS', name: 'iShares TIPS Bond ETF', category: 'bonds', description: 'Treasury inflation-protected securities' },
  { symbol: 'EMB', name: 'iShares J.P. Morgan USD Emerging Markets Bond ETF', category: 'bonds', description: 'Emerging market bond ETF' },
  { symbol: 'VCIT', name: 'Vanguard Intermediate-Term Corporate Bond ETF', category: 'bonds', description: 'Corporate bond ETF' },
  { symbol: 'VMBS', name: 'Vanguard Mortgage-Backed Securities ETF', category: 'bonds', description: 'Mortgage-backed securities ETF' },
  { symbol: 'MUB', name: 'iShares National Muni Bond ETF', category: 'bonds', description: 'Municipal bond ETF' },
  { symbol: 'VTEB', name: 'Vanguard Tax-Exempt Bond ETF', category: 'bonds', description: 'Tax-exempt bond ETF' },
  { symbol: 'BKLN', name: 'Invesco Senior Loan ETF', category: 'bonds', description: 'Senior loan ETF' },
  { symbol: 'FLOT', name: 'iShares Floating Rate Bond ETF', category: 'bonds', description: 'Floating rate bond ETF' },

  // Cryptocurrencies
  { symbol: 'BTC-USD', name: 'Bitcoin', category: 'crypto', description: 'Leading cryptocurrency' },
  { symbol: 'ETH-USD', name: 'Ethereum', category: 'crypto', description: 'Smart contract platform' },
  { symbol: 'BNB-USD', name: 'Binance Coin', category: 'crypto', description: 'Binance exchange token' },
  { symbol: 'XRP-USD', name: 'XRP', category: 'crypto', description: 'Digital payment protocol' },
  { symbol: 'ADA-USD', name: 'Cardano', category: 'crypto', description: 'Blockchain platform' },
  { symbol: 'SOL-USD', name: 'Solana', category: 'crypto', description: 'High-performance blockchain' },
  { symbol: 'DOGE-USD', name: 'Dogecoin', category: 'crypto', description: 'Meme cryptocurrency' },
  { symbol: 'DOT-USD', name: 'Polkadot', category: 'crypto', description: 'Multi-chain blockchain' },
  { symbol: 'AVAX-USD', name: 'Avalanche', category: 'crypto', description: 'Smart contracts platform' },
  { symbol: 'SHIB-USD', name: 'Shiba Inu', category: 'crypto', description: 'Meme cryptocurrency' },
  { symbol: 'MATIC-USD', name: 'Polygon', category: 'crypto', description: 'Ethereum scaling solution' },
  { symbol: 'LTC-USD', name: 'Litecoin', category: 'crypto', description: 'Peer-to-peer cryptocurrency' },
  { symbol: 'UNI-USD', name: 'Uniswap', category: 'crypto', description: 'Decentralized exchange token' },
  { symbol: 'LINK-USD', name: 'Chainlink', category: 'crypto', description: 'Decentralized oracle network' },
  { symbol: 'BCH-USD', name: 'Bitcoin Cash', category: 'crypto', description: 'Bitcoin fork' },
  { symbol: 'ATOM-USD', name: 'Cosmos', category: 'crypto', description: 'Blockchain ecosystem' },
  { symbol: 'XLM-USD', name: 'Stellar', category: 'crypto', description: 'Cross-border payments' },
  { symbol: 'VET-USD', name: 'VeChain', category: 'crypto', description: 'Supply chain management' },
  { symbol: 'ICP-USD', name: 'Internet Computer', category: 'crypto', description: 'Decentralized internet' },
  { symbol: 'FIL-USD', name: 'Filecoin', category: 'crypto', description: 'Decentralized storage' },
  { symbol: 'TRX-USD', name: 'TRON', category: 'crypto', description: 'Decentralized entertainment' },
  { symbol: 'ETC-USD', name: 'Ethereum Classic', category: 'crypto', description: 'Original Ethereum chain' },
  { symbol: 'XMR-USD', name: 'Monero', category: 'crypto', description: 'Privacy-focused cryptocurrency' },
  { symbol: 'ALGO-USD', name: 'Algorand', category: 'crypto', description: 'Pure proof-of-stake blockchain' },
  { symbol: 'HBAR-USD', name: 'Hedera', category: 'crypto', description: 'Hashgraph consensus' },

  // Commodities
  { symbol: 'GC=F', name: 'Gold Futures', category: 'commodities', description: 'Precious metal futures' },
  { symbol: 'SI=F', name: 'Silver Futures', category: 'commodities', description: 'Precious metal futures' },
  { symbol: 'CL=F', name: 'Crude Oil Futures', category: 'commodities', description: 'Energy commodity futures' },
  { symbol: 'NG=F', name: 'Natural Gas Futures', category: 'commodities', description: 'Energy commodity futures' },
  { symbol: 'HG=F', name: 'Copper Futures', category: 'commodities', description: 'Industrial metal futures' },
  { symbol: 'PL=F', name: 'Platinum Futures', category: 'commodities', description: 'Precious metal futures' },
  { symbol: 'PA=F', name: 'Palladium Futures', category: 'commodities', description: 'Precious metal futures' },
  { symbol: 'ZC=F', name: 'Corn Futures', category: 'commodities', description: 'Agricultural commodity futures' },
  { symbol: 'ZW=F', name: 'Wheat Futures', category: 'commodities', description: 'Agricultural commodity futures' },
  { symbol: 'ZS=F', name: 'Soybean Futures', category: 'commodities', description: 'Agricultural commodity futures' },
  { symbol: 'SB=F', name: 'Sugar Futures', category: 'commodities', description: 'Agricultural commodity futures' },
  { symbol: 'KC=F', name: 'Coffee Futures', category: 'commodities', description: 'Agricultural commodity futures' },
  { symbol: 'CC=F', name: 'Cocoa Futures', category: 'commodities', description: 'Agricultural commodity futures' },
  { symbol: 'CT=F', name: 'Cotton Futures', category: 'commodities', description: 'Agricultural commodity futures' },
  { symbol: 'LBS=F', name: 'Lumber Futures', category: 'commodities', description: 'Building material futures' },
  { symbol: 'HE=F', name: 'Lean Hogs Futures', category: 'commodities', description: 'Livestock futures' },
  { symbol: 'LE=F', name: 'Live Cattle Futures', category: 'commodities', description: 'Livestock futures' },
  { symbol: 'GF=F', name: 'Feeder Cattle Futures', category: 'commodities', description: 'Livestock futures' },
  { symbol: 'RB=F', name: 'RBOB Gasoline Futures', category: 'commodities', description: 'Energy commodity futures' },
  { symbol: 'HO=F', name: 'Heating Oil Futures', category: 'commodities', description: 'Energy commodity futures' },
  { symbol: 'ZM=F', name: 'Soybean Meal Futures', category: 'commodities', description: 'Agricultural commodity futures' },
  { symbol: 'ZL=F', name: 'Soybean Oil Futures', category: 'commodities', description: 'Agricultural commodity futures' },
  { symbol: 'ZO=F', name: 'Oats Futures', category: 'commodities', description: 'Agricultural commodity futures' },
  { symbol: 'ZR=F', name: 'Rice Futures', category: 'commodities', description: 'Agricultural commodity futures' },
  { symbol: 'DX=F', name: 'US Dollar Index Futures', category: 'commodities', description: 'Currency index futures' },
];

export const CATEGORIES = [
  { key: 'stocks', name: 'Saham', icon: '📈', description: 'Saham perusahaan publik' },
  { key: 'indices', name: 'Indeks', icon: '📊', description: 'Indeks pasar saham' },
  { key: 'bonds', name: 'Obligasi', icon: '🏦', description: 'Obligasi dan surat hutang' },
  { key: 'crypto', name: 'Kripto', icon: '₿', description: 'Mata uang kripto' },
  { key: 'commodities', name: 'Komoditas', icon: '🥇', description: 'Komoditas dan futures' },
] as const;

export function getInstrumentsByCategory(category: string) {
  return FINANCIAL_INSTRUMENTS.filter(instrument => instrument.category === category);
}